### ISSUE TITLE
[FEATURE] Search input at "Multiplier" section

### ISSUE THREAD

**Issue by Alvaroggm123** [JensvandeWiel/ArkAscendedServerManager#162] opened 2023-11-26 17:46 UTC
It is hard to locate a specific parameter with just scrolling the Multiplier section. 

I thought that the things can be simplified by let in the users to search a configuration parameter by typing in on a Search box.

**Comment by jordan-dalby** [comment] 2023-11-29 12:33
#149

**Comment by JensvandeWiel** [comment] 2023-11-30 09:03
Duplicate of #149

**Closed by JensvandeWiel** 2023-11-30 09:03 UTC
Labels: enhancement
